name: Mike Thomas
favicon: null
layout_spectrum: 0.63113
typography_spectrum: 0.28192
title: Mike Thomas
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ac0000'
    - '#dac46e'
    - '#51744a'
    - '#283627'
    - '#e07600'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
