name: Mike Thomas
favicon: null
layout_spectrum: 0.64008
typography_spectrum: 0.65353
title: Mike Thomas
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.04680851
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
